import { useEffect, useRef } from "react";
import { useTranslation } from "react-i18next";
import { Loader2, RefreshCw, Sparkles } from "lucide-react";

import { Button } from "@/components/ui/button";
import { useLessonSummary } from "@/hooks/useLessonSummary";

type Props = {
  lessonId: string | null;
  courseId: string | null;
  completed: boolean;
  locale?: "vi" | "en";
};

export function LessonRecapCard({ lessonId, courseId, completed, locale }: Props) {
  const { t } = useTranslation("courses");
  const { summary, loading, generating, error, generate } = useLessonSummary({
    lessonId,
    courseId,
    locale,
  });

  // Auto-trigger generation the first time we observe (completed + no existing summary).
  // The ref keeps us from re-firing across re-renders.
  const autoGeneratedFor = useRef<string | null>(null);
  useEffect(() => {
    if (!completed || !lessonId || !courseId) return;
    if (loading || generating) return;
    if (summary) return;
    if (error) return;
    if (autoGeneratedFor.current === lessonId) return;
    autoGeneratedFor.current = lessonId;
    void generate();
  }, [completed, courseId, error, generate, generating, lessonId, loading, summary]);

  // Reset auto-trigger guard when lesson changes
  useEffect(() => {
    autoGeneratedFor.current = null;
  }, [lessonId]);

  if (!completed || !lessonId) return null;
  if (loading) return null;

  if (generating && !summary) {
    return (
      <div className="mx-4 mt-4 rounded-2xl border border-border-subtle bg-surface-raised p-5 sm:mx-6">
        <div className="flex items-center gap-2 text-sm text-foreground-muted">
          <Loader2 className="w-4 h-4 animate-spin" aria-hidden />
          {t("detail.learn.recap.generating", {
            defaultValue: "Cora đang tóm tắt bài học…",
          })}
        </div>
      </div>
    );
  }

  if (error && !summary) {
    return (
      <div className="mx-4 mt-4 rounded-2xl border border-border-subtle bg-surface-raised p-5 sm:mx-6">
        <p className="text-sm text-foreground-muted">
          {t("detail.learn.recap.error", {
            defaultValue: "Cora chưa thể tóm tắt bài học lúc này.",
          })}
        </p>
        <Button
          variant="outline"
          size="sm"
          className="mt-3"
          onClick={() => void generate({ force: true })}
        >
          <RefreshCw className="w-4 h-4" aria-hidden />
          {t("detail.learn.recap.retry", { defaultValue: "Thử lại" })}
        </Button>
      </div>
    );
  }

  if (!summary) return null;

  const hasTips = summary.practicalTips.length > 0;

  return (
    <div className="mx-4 mt-4 overflow-hidden rounded-2xl border border-border-subtle bg-surface-raised shadow-card sm:mx-6">
      <div className="flex items-center justify-between gap-2 border-b border-border-subtle px-5 py-3">
        <div className="flex items-center gap-2 text-sm font-semibold text-foreground">
          <Sparkles className="w-4 h-4 text-primary" aria-hidden />
          {t("detail.learn.recap.title", { defaultValue: "Cora's recap" })}
        </div>
        <Button
          variant="ghost"
          size="sm"
          onClick={() => void generate({ force: true })}
          disabled={generating}
          title={t("detail.learn.recap.regenerate", { defaultValue: "Regenerate" })}
        >
          {generating ? (
            <Loader2 className="w-4 h-4 animate-spin" aria-hidden />
          ) : (
            <RefreshCw className="w-4 h-4" aria-hidden />
          )}
          <span className="ml-1 text-xs">
            {t("detail.learn.recap.regenerate", { defaultValue: "Regenerate" })}
          </span>
        </Button>
      </div>

      <div className="px-5 py-4 space-y-4 text-[14.5px] leading-[1.7]">
        <section>
          <h4 className="text-xs font-semibold uppercase tracking-wide text-foreground-muted">
            {t("detail.learn.recap.keyPointsLabel", {
              defaultValue: "Key takeaways",
            })}
          </h4>
          <ul className="mt-2 space-y-1.5 list-disc pl-5 text-foreground">
            {summary.keyPoints.map((point, idx) => (
              <li key={idx}>{point}</li>
            ))}
          </ul>
        </section>

        {hasTips ? (
          <section>
            <h4 className="text-xs font-semibold uppercase tracking-wide text-foreground-muted">
              {t("detail.learn.recap.practicalTipsLabel", {
                defaultValue: "Practical tips",
              })}
            </h4>
            <ul className="mt-2 space-y-1.5 list-disc pl-5 text-foreground">
              {summary.practicalTips.map((tip, idx) => (
                <li key={idx}>{tip}</li>
              ))}
            </ul>
          </section>
        ) : null}
      </div>
    </div>
  );
}
