export const JOB_ROLE_SLUGS = [
  "frontend-engineering",
  "backend-engineering",
  "fullstack-engineering",
  "mobile-engineering",
  "blockchain-engineering",
  "smart-contract-engineering",
  "software-architecture",
  "general-software-engineering",
  "devops",
  "site-reliability-engineering",
  "platform-engineering",
  "cloud-engineering",
  "ai-engineering",
  "machine-learning-engineering",
  "data-engineering",
  "data-science",
  "cybersecurity",
  "qa-engineering",
  "developer-relations",
  "technical-writing",
  "solutions-engineering",
  "technical-product-management",
  "engineering-management",
] as const;

export const JOB_DOMAIN_SLUGS = [
  "ai", "web3", "fintech", "saas", "cloud", "developer-tools",
  "cybersecurity", "gaming", "ecommerce", "edtech", "healthtech",
  "data-infrastructure", "enterprise-software", "open-source", "consumer",
  "robotics", "iot", "general-software",
] as const;

export const JOB_SKILL_ALIASES: Record<string, string[]> = {
  javascript: ["javascript", "js"],
  typescript: ["typescript", "ts"],
  python: ["python"],
  rust: ["rust"],
  go: ["golang", "go"],
  java: ["java"],
  kotlin: ["kotlin"],
  swift: ["swift"],
  solidity: ["solidity"],
  react: ["react.js", "reactjs", "react"],
  nextjs: ["next.js", "nextjs"],
  vue: ["vue.js", "vuejs", "vue"],
  angular: ["angular"],
  svelte: ["svelte"],
  tailwind: ["tailwind css", "tailwind"],
  nodejs: ["node.js", "nodejs"],
  nestjs: ["nest.js", "nestjs"],
  django: ["django"],
  fastapi: ["fastapi"],
  graphql: ["graphql"],
  grpc: ["grpc"],
  postgresql: ["postgresql", "postgre sql", "postgres"],
  mysql: ["mysql"],
  mongodb: ["mongo db", "mongodb"],
  redis: ["redis"],
  docker: ["docker"],
  kubernetes: ["kubernetes", "k8s"],
  aws: ["amazon web services", "aws"],
  gcp: ["google cloud platform", "google cloud", "gcp"],
  azure: ["azure"],
  terraform: ["terraform"],
  "machine-learning": ["machine learning"],
  llm: ["large language models", "large language model", "llms", "llm"],
  pytorch: ["pytorch"],
  tensorflow: ["tensorflow"],
  ethereum: ["ethereum"],
  solana: ["solana"],
  "smart-contracts": ["smart contracts", "smart contract"],
};

export const JOB_SKILL_SLUGS = Object.keys(JOB_SKILL_ALIASES);

export const ROLE_PATTERNS: Array<[string, RegExp]> = [
  ["smart-contract-engineering", /\bsmart[- ]?contract\b/i],
  ["blockchain-engineering", /\b(blockchain|web3|protocol)\b.*\b(engineer|developer)\b|\b(solana|ethereum)\b.*\b(engineer|developer)\b/i],
  ["frontend-engineering", /\b(front[- ]?end|ui engineer|web engineer)\b/i],
  ["backend-engineering", /\b(back[- ]?end|server[- ]?side|api engineer)\b/i],
  ["fullstack-engineering", /\b(full[- ]?stack)\b/i],
  ["mobile-engineering", /\b(mobile|ios|android)\b.*\b(engineer|developer)\b/i],
  ["site-reliability-engineering", /\b(site reliability|sre)\b/i],
  ["platform-engineering", /\bplatform engineer/i],
  ["cloud-engineering", /\bcloud engineer/i],
  ["devops", /\b(devops|devsecops|infrastructure engineer)\b/i],
  ["machine-learning-engineering", /\b(machine learning|ml) engineer\b/i],
  ["ai-engineering", /\b(ai|artificial intelligence|llm) engineer\b/i],
  ["data-engineering", /\bdata engineer/i],
  ["data-science", /\bdata scientist/i],
  ["cybersecurity", /\b(security|cybersecurity|application security)\b.*\b(engineer|researcher)\b/i],
  ["qa-engineering", /\b(qa|quality assurance|test automation|sdet)\b/i],
  ["developer-relations", /\b(developer relations|devrel|developer advocate)\b/i],
  ["technical-writing", /\btechnical writer/i],
  ["solutions-engineering", /\bsolutions? (engineer|architect)\b/i],
  ["technical-product-management", /\b(technical )?product manager\b/i],
  ["engineering-management", /\b(engineering manager|head of engineering|director of engineering)\b/i],
  ["software-architecture", /\bsoftware architect/i],
  ["general-software-engineering", /\b(software|product|systems?)\b.*\b(engineer|developer)\b|\b(engineer|developer)\b/i],
];

export const DOMAIN_PATTERNS: Array<[string, RegExp]> = [
  ["ai", /\b(ai|artificial intelligence|machine learning|llm|generative ai)\b/i],
  ["web3", /\b(web3|blockchain|crypto|defi|smart contract|ethereum|solana)\b/i],
  ["fintech", /\b(fintech|payments?|banking|financial services)\b/i],
  ["cloud", /\b(cloud infrastructure|cloud platform|aws|gcp|azure)\b/i],
  ["developer-tools", /\b(developer tools?|developer experience|devtools|sdk|api platform)\b/i],
  ["cybersecurity", /\b(cybersecurity|application security|infosec|security platform)\b/i],
  ["gaming", /\b(gaming|game engine|gameplay)\b/i],
  ["ecommerce", /\b(e-?commerce|marketplace)\b/i],
  ["edtech", /\b(edtech|education technology|learning platform)\b/i],
  ["healthtech", /\b(healthtech|healthcare technology|digital health)\b/i],
  ["data-infrastructure", /\b(data infrastructure|database|data platform|analytics platform)\b/i],
  ["open-source", /\bopen[- ]source\b/i],
  ["robotics", /\brobotics?\b/i],
  ["iot", /\b(iot|internet of things)\b/i],
  ["saas", /\bsaas\b/i],
];

export const CLEARLY_NON_TECH_TITLE = /\b(accountant|bookkeeper|cashier|warehouse|driver|nurse|bartender|waiter|waitress|receptionist|administrative assistant|sales representative|real estate|store manager)\b/i;
