import { useLearningTranslation } from "@/features/learning/useLearningTranslation";
import { Button } from "@/components/ui/button";
import type { SectionQuestion } from "@/types/questions";
import { TextField, OrderedCard } from "./EditorFields";
import { moveItem } from "./order";
export function QuizBuilder({ questions, onChange, courseId, lessonId }: { questions: SectionQuestion[]; onChange(questions: SectionQuestion[]): void; courseId: string; lessonId: string }) {
  const { t } = useLearningTranslation();
  const patch = (index:number, value:Partial<SectionQuestion>) => onChange(questions.map((q,i)=>i===index?{ ...q,...value }:q));
  return <div id="learning-questions" tabIndex={-1} className="space-y-4">{questions.map((q,index) => <OrderedCard key={q.id} index={index} total={questions.length} onMove={d => onChange(moveItem(questions,index,d).map((v,order)=>({ ...v,order })))} onRemove={() => onChange(questions.filter((_,i)=>i!==index))}><TextField id={`learning-question-${q.id}`} label={t("learning.question")} value={q.question} onChange={question => patch(index,{ question })} />{q.options.map((option,i) => <div key={option.id} className="flex items-center gap-3"><input type="radio" name={`correct-${q.id}`} aria-label={`${t("learning.correctOption")} ${i+1}`} checked={q.correct_index===i} onChange={() => patch(index,{ correct_index:i })} /><div className="flex-1"><TextField id={`learning-option-${q.id}-${option.id}`} label={`${t("learning.option")} ${i+1}`} value={option.text} onChange={text => patch(index,{ options:q.options.map((o,j)=>j===i?{ ...o,text }:o) })} /></div></div>)}<Button type="button" variant="outline" onClick={() => patch(index,{ options:[...q.options,{ id:crypto.randomUUID(),text:"" }] })}>{t("learning.addOption")}</Button><TextField label={t("learning.explanation")} multiline value={q.explanation ?? ""} onChange={explanation => patch(index,{ explanation })} /></OrderedCard>)}<Button type="button" variant="outline" onClick={() => onChange([...questions,{ id:crypto.randomUUID(),course_id:courseId,section_id:lessonId,order:questions.length,type:"mcq",question:"",options:[{ id:"a",text:"" },{ id:"b",text:"" }],correct_index:0 }])}>{t("learning.addQuestion")}</Button></div>;
}
